name: ci-cd

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Linter
        uses: psf/black@stable

      - name: Test with pytest
        run: poetry run pytest tests/ --cov=sysloss --cov-report=xml

      - name: Use Codecov to track coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml   # coverage report

      #- name: Coverage badge
      #  uses: tj-actions/coverage-badge-py@v2

      #- name: Build documentation
      #  run: poetry run make html --directory docs/

  